Question1Screen

<Question1Screen>:
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "What is 9+10?"
        BoxLayout:
            Button:
                text: "This meme is not funny, its long dead."
            Button:
                text: "twenty-one!"
            Button:
                text: "19"
<CorrectScreen>:
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Correct!"